# Generated by Django 4.1 on 2022-08-29 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_bio_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
