# Generated by Django 4.1 on 2022-08-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
