# Generated by Django 4.1 on 2022-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_followers_posts_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
