# Generated by Django 4.1 on 2022-09-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_followers_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
