# Generated by Django 4.1 on 2022-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_posts_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
