# Generated by Django 4.2.3 on 2023-07-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_rename_followers_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='liked_by',
        ),
    ]
