# Generated by Django 4.1 on 2023-07-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_rename_like_like_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='followed_by',
        ),
    ]
