# Generated by Django 4.1 on 2023-07-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_rename_followers_follower_followed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
