name: Testing
on: push

jobs:
    network:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2            
          - name: Run Django unit tests
            env:
              SECRET_KEY: ${{ secrets.SECRET_KEY }}
              NAME: ${{ secrets.NAME }}
              USER_NAME: ${{ secrets.USER_NAME }}
              PASSWORD: ${{ secrets.PASSWORD }}
              HOST: ${{ secrets.HOST }}
              PORT: ${{ secrets.PORT }}
            run: |
              pip3 install --user -r requirements.txt
              python3 manage.py test network