name: Testing
on: push

jobs:
    network:
        runs-on: ubuntu-latest
        environment: ci_test
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Run Django unit tests
            run: |
              pip3 install --user -r requirements.txt
              python3 manage.py test network