name: Testing
on: push

jobs:
    network:
        runs-on: ubuntu-latest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: ${{ secrets.NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Print Environment Variables
            run: |
              echo "SECRET_KEY: $SECRET_KEY"
              echo "NAME: $NAME"
              echo "USER_NAME: $USER_NAME"
              echo "PASSWORD: $PASSWORD"
              echo "HOST: $HOST"
              echo "PORT: $PORT"
          # - name: Run Django unit tests
          #   run: |
          #     pip3 install --user -r requirements.txt
          #     python3 manage.py test network