name: Testing
on: push

jobs:
    network:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run Django unit tests
              env:
                NAME: ${{ secrets.NAME }}
              run: |
                pip3 install --user -r requirements.txt
                python3 manage.py test network