name: Testing
on: push

jobs:
    network:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Print Environment Variables
            env:
              SECRET_KEY: ${{ secrets.SECRET_KEY }}
            run: |
              echo "SECRET_KEY: $SECRET_KEY"
          # - name: Run Django unit tests
          #   run: |
          #     pip3 install --user -r requirements.txt
          #     python3 manage.py test network